title: Welcome to my Blog | Dharmang Andhariya
author: Dharmang Andhariya
email: ecdh130 at gmail dot com
description: > # this means to ignore newlines until "baseurl:"
  Welcom to my Blog Dharmang Andhariya.

# social links
twitter_username: dharmang
github_username:  dharmang

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
